### ISSUE TITLE
enable filtering for a single crate in a larger workspace

### ISSUE THREAD

**Issue by hdb3** [Patryk27/clippy-dirty#1]
Feature request
Extension to enable message filtering for a single crate in a larger workspace.
Motivation: similar to existing - selectively analyse and apply clippy for a subset of a large project.

Caveat: there may be another way to do this e.g. at the crate level. 'cargo check' is documented to allow --package option.
But that does not  work (for me, at least - it just checks the entire workspace).

**Comment by Patryk27** [comment]
Thanks for reporting - I've improved the script, so that now you can do:
```bash
clippy-dirty -- -p some-workspace-crate
```
It works by passing all those additional parameters into `clippy`, so you can use `-p ...`, `--all-features` and all the other options.

Feel free to re-open this issue if you find anything not working as intended.
