### ISSUE TITLE
Add option to ignore untracked files

### ISSUE THREAD

**Issue by sukhmel** [Patryk27/clippy-dirty#2]
When I run clippy-dirty it discovers 65 dirty files, 63 of them are untracked, 1 is really modified, and 1 more I don't know what is.

**Comment by Patryk27** [comment]
Hi, thanks for letting me know - I've just implemented a switch called `-u` that tells `clippy-dirty` to ignore untracked files 🙂 

If that's not what you meant or the switch isn't working as expected, please feel free to re-open this issue.
