### ISSUE TITLE
jq compile error on weird filenames

### ISSUE THREAD

**Issue by sukhmel** [Patryk27/clippy-dirty#3]
I had a file named `uc\?export\=download\&id\=some` in my repo because of some mistakes in handling commands, and this file made `clippy-dirty` fail on launching clippy step with a following message:

```
jq: error: syntax error, unexpected IDENT, expecting ';' or ')' (Unix shell quting issues?) at <top-level>, line 4:
            |  select(any(.message.spans[]; false or .file_name == ... or ""uc\\?export\\=download\\&id\\=some""
```

Here I omitted full line of filenames, but note that there are doubled double qoutes around last filename

This issue is now fixed for me as I didn't really need the file that broke everything, and so deleted it, but someone could possibly run into the issue.

**Comment by Patryk27** [comment]
Hi, thanks for reporting - I've pushed a fix 🙂 
Feel free to re-open this issue if this happens again.
